college_id: "NMC_001"
base_url: "https://nmc.ac.in/"
faculty_keywords: ["faculty", "staff", "teaching", "members", "profile", "department-staff"]
output_file: "nmc_structured_data.json"

seed_urls:
  - "https://nmc.ac.in/nehru-about-history.php"
  - "https://nmc.ac.in/nehru-about-visionmission.php"
  - "https://nmc.ac.in/nehru-academics-annualreports.php"
  - "https://nmc.ac.in/nehru-iqac-naaccertificates.php"
  - "https://nmc.ac.in/nehru-about-milestones.php"
  - "https://nmc.ac.in/nehru-contactus.php"
  - "https://nmc.ac.in/nehru-organi-educational.php"
  - "https://nmc.ac.in/nehru-organi-collegecommittee.php"
  - "https://nmc.ac.in/nehru-organi-financecommittee.php"
  - "https://nmc.ac.in/nehru-organi-goveringbody.php"
  - "https://nmc.ac.in/nehru-about-president.php"
  - "https://nmc.ac.in/nehru-about-secretary.php"
  - "https://nmc.ac.in/nehru-about-principal.php"
  - "https://nmc.ac.in/nehru-academics-dean.php"
  - "https://nmc.ac.in/nehru-academics-rules&regulations.php"
  - "https://nmc.ac.in/nehru-academics-programmes1.php"
  - "https://nmc.ac.in/nehru-academics-depart-maths.php"
  - "https://nmc.ac.in/nehru-academics-depart-physics.php"
  - "https://nmc.ac.in/nehru-academics-depart-chemistry.php"
  - "https://nmc.ac.in/nehru-academics-depart-zoology.php"
  - "https://nmc.ac.in/nehru-academics-depart-botany.php"
  - "https://nmc.ac.in/nehru-academics-depart-nutri.php"
  - "https://nmc.ac.in/nehru-academics-depart-biotechnology.php"
  - "https://nmc.ac.in/nehru-academics-depart-hotelmanagement.php"
  - "https://nmc.ac.in/nehru-academics-depart-artificial.php"
  - "https://nmc.ac.in/nehru-academics-depart-datascience.php"
  - "https://nmc.ac.in/nehru-academics-depart-computerscience.php"
  - "https://nmc.ac.in/nehru-academics-depart-commerce.php"
  - "https://nmc.ac.in/nehru-academics-depart-english.php"
  - "https://nmc.ac.in/nehru-academics-depart-tamil.php"
  - "https://nmc.ac.in/nehru-academics-depart-economics.php"
  - "https://nmc.ac.in/nehru-academics-depart-bba.php"
  - "https://nmc.ac.in/nmcmca/index.php"