"""Qdrant vector retrieval service with tenant isolation support."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, validate_call
from qdrant_client import AsyncQdrantClient
from qdrant_client.http import models as qmodels
from qdrant_client.http.exceptions import UnexpectedResponse

from src.api import application
from src.core.logging import setup_logger

logger = setup_logger(__name__)

class QdrantRetrieverConfig(BaseModel):
    """Configuration schema for Qdrant retriever initialization."""

    collection_name: str = Field(..., min_length=1, description="Target collection name")
    top_k: int = Field(5, ge=1, le=100, description="Number of top document chunks to retrieve")
    score_threshold: float = Field(0.0, ge=0.0, le=1.0, description="Minimum similarity score cutoff")

class RetrivedDocument(BaseModel):
    """Schema for a retrieved text chunk payload."""

    document_id: str 
    text: str
    score: float
    metadata: Dict[str, Any] = Field(default_factory=dict)

class QdrantRetriever:
    '''
    Service class for executing vector similarity searches in Qdrant with tenant isolation.
    '''
    @validate_call
    def __init__(self, config: QdrantRetrieverConfig):
        '''
        Initializes the qdrant client connection and search settings.

        Args:
            config: validated QdrantRetrieverConfig object.
        '''
        logger.info(f"Initializing Qdrant client for collection '{config.collection_name}'")
        self.client: AsyncQdrantClient = application.get().qdrant_client
        self.collection_name = config.collection_name
        self.top_k = config.top_k
        self.score_threshold = config.score_threshold

    async def retrieve(self, query_vector: List[float], tenant_id: str) -> List[RetrivedDocument]:
        '''
        Queries Qdrant for matching vectors belonging strictly to the specified tenant.

        Args:
            query_vector: Dense vector list generated by the query embedder.
            tenant_id: Active tenant identifier used for strict payload filtering.

        Returns:
            List[RetrivedDocument]: List of relevant document chunks above the score threshold.
        '''
        if not query_vector:
            logger.error("Empty query vector supplied to Qdrant retriever.")
            raise ValueError("Query vector cannot be empty.")

        clean_tenant_id = tenant_id.strip()
        if not clean_tenant_id:
            logger.error("Missing or blank tenant_id supplied for vector retrieval.")
            raise ValueError("Tenant ID is required for multi-tenant isolation.")

        logger.info(f"Executing Qdrant search for tenant '{clean_tenant_id}' (top_k={self.top_k})")

        # construct payload fiter for strict tenant isolation
        tenant_filter = qmodels.Filter(
            must=[
                qmodels.FieldCondition(
                    key="tenant_id",
                    match=qmodels.MatchValue(value=clean_tenant_id),
                )
            ]
        )

        try:
            results = await self.client.query_points(
                collection_name=self.collection_name,
                query=query_vector,
                query_filter=tenant_filter,
                limit=self.top_k,
                score_threshold=self.score_threshold,
            )

            retrieved_docs: List[RetrivedDocument] = []
            for point in results.points:
                payload = point.payload or {}
                text = payload.get("text", "")
                doc_id = payload.get("document_id", str(point.id))

                retrieved_docs.append(
                    RetrivedDocument(
                        document_id=doc_id,
                        text=text,
                        score=point.score,
                        metadata={k: v for k, v in payload.items() if k not in ("text", "tenant_id")},
                    )
                )

            logger.info(f"Retrieved {len(retrieved_docs)} matching documents for tenant '{clean_tenant_id}'")
            return retrieved_docs

        except UnexpectedResponse as e:
            logger.error(f"Qdrant API error during search: {str(e)}", exc_info=True)
            raise RuntimeError(f"Qdrant database error: {str(e)}") from e
        
        except Exception as e:
            logger.error(f"Unexpected error during vector search: {str(e)}", exc_info=True)
            raise RuntimeError(f"Failed to retrieve context from Qdrant: {str(e)}") from e